### ISSUE TITLE
Importing internal function from uwot

### ISSUE THREAD

**Issue by jlmelville** [ycli1995/bbknnR#1]
Hello, I am the maintainer of the [uwot](https://cran.r-project.org/package=uwot) package. I recently attempted to submit a new version of `uwot` to CRAN to ensure it keeps working with a forthcoming version of the [Matrix](https://cran.r-project.org/package=Matrix). Unfortunately, the submission failed because a change to an internal function (`fuzzy_simplicial_set`) broke your package.

A forthcoming submission will fix this issue, but please don't import internal functions from `uwot` into your packages if they are intended for use with CRAN. The reason `fuzzy_simplicial_set` is not in the `NAMESPACE` is because I don't want to promise to provide backwards compatibility for that function. It's also (at best) against the spirit of the [CRAN submission policies](https://cran.r-project.org/web/packages/policies.html):

> - CRAN packages should use only the public API. Hence they should not use entry points not declared as API in installed headers nor .Internal() nor .Call() etc calls to base packages. Also, ::: should not be used to access undocumented/internal objects in base packages (nor should other means of access be employed). Such usages can cause packages to break at any time, even in patched versions of R.

If you need the `fuzzy_simplicial_set` functionality, I would be happy to work on making it suitable for exporting as part of the public API and then I *will* commit to maintaining backwards compatibility. We can either discuss your needs here or please [open an issue at the uwot repository](https://github.com/jlmelville/uwot/issues).

**Comment by ycli1995** [comment]
Hi, James
  Sorry for the delayed reply. I have opened a new issue https://github.com/jlmelville/uwot/issues/96#issue-1343165132.

Yuchen Li

**Comment by ycli1995** [comment]
> I have added a new function to `uwot`'s public API: `similarity_graph` (NB: this is not available on CRAN yet, only via github).
> 
> @ycli1995 this would be a fairly straightforward conversion from your current use of `fuzzy_simplicial_set`. Where your `compute_connectivities_umap` function currently runs:
> 
> ```r
>   cnts <- fuzzy_simplicial_set(
>     nn = list(idx = knn_index, dist = knn_dist),
>     set_op_mix_ratio = set_op_mix_ratio,
>     local_connectivity = local_connectivity
>   )
> ```
> 
> you would instead use:
> 
> ```r
>   cnts <- similarity_graph(
>     nn_method = list(idx = knn_index, dist = knn_dist),
>     set_op_mix_ratio = set_op_mix_ratio,
>     local_connectivity = local_connectivity
>   )
> ```
> 
> So the only change required (apart from the function change) is that the `nn` parameter should be renamed `nn_method`.
> 
> On my local install of `bbknnR`, when I run the example in your vignette with `panc8_small`, the `cnts` matrix is identical whether I use `fuzzy_simplicial_set` or `similarity_graph` and the final images are identical, but obviously you should run your own tests when you are able to.
> 
> We can continue this discussion at [ycli1995/bbknnR#1](https://github.com/ycli1995/bbknnR/issues/1) in terms of what the timing will be of new submissions to CRAN and other changes (e.g. minimum version of uwot required, removing the call to `getFromNamespace` in your package and so on).

I've seen your newest commit on https://github.com/jlmelville/uwot/issues/96, thank you so much!

Currently, perhaps I should first submit a new `bbknnR` to CRAN, where the `fuzzy_simplicial_set` call is replaced by `umap(n_epochs = 0, ret_extra = c("fgraph"), init = NULL)` (I've tested it on my local development environment and it worked well), so that the modified `uwot` with `similarity_graph()` can pass the submission check for CRAN.

Do you think this approach should work?

**Comment by jlmelville** [comment]
> Currently, perhaps I should first submit a new `bbknnR` to CRAN, where the `fuzzy_simplicial_set` call is replaced by `umap(n_epochs = 0, ret_extra = c("fgraph"), init = NULL)` (I've tested it on my local development environment and it worked well), so that the modified `uwot` with `similarity_graph()` can pass the submission check for CRAN.
> 
> Do you think this approach should work?

I am not sure that using `init = NULL` will work on the current release of `uwot`. When I tried it, it gave an error. Right now, I would recommend using `umap(n_epochs = 0, ret_extra = c("fgraph"), init = "rand")` as the fastest safe way to generate what you need.

However, I have carried out nearly all the pre-checks I need to create version 0.1.14 and submit it to CRAN. The difficult part is that submissions more frequently than every 2-3 months are frowned upon by the CRAN submission team. However as this is part of preventing `bbknnR` from being removed from CRAN, I hope they will allow it.

So I plan to submit uwot 0.1.14 to CRAN either today or tomorrow. I will report back here depending on what the response is. It will probably take a couple of days at the very least.

**Comment by ycli1995** [comment]
Hi, James. I've try your advice for setting `init = "rand"` and it worked well for me with `uwot=0.1.13`. 

A new `bbknnR` has been commit to github https://github.com/ycli1995/bbknnR/commit/6ba71fc46d43ce5d3c50d4d946831e7f75a11cf6, where `compute_connectivities_umap` now import public function `uwot::umap()` to make sure it will always follow the [CRAN submission policies](https://cran.r-project.org/web/packages/policies.html).

Since you have been ready for submission of `uwot 0.1.14` to CRAN, I will wait for your response about it here. Still, I think the new `bbknnR` could be the plan B in case of `uwot 0.1.14` fail the submission, since `uwot 0.1.13` has been on CRAN. Therefore, please let me know if you need me to submit the new version of `bbknnR` to CRAN.

Thank you!

**Comment by jlmelville** [comment]
I submitted 0.1.14 shortly after my last message here. I will keep you updated. If the submission isn't accepted then I agree submitting a new version of `bbknnR` with the current commit is the best plan.

**Comment by jlmelville** [comment]
Good news, version 0.1.14 of `uwot` is [now on CRAN](https://cran.r-project.org/package=uwot), so you should be able to start testing the use of `similarity_graph`.

**Comment by ycli1995** [comment]
Hi, James. A new `bbknnR` of version `1.0.1`, which imports `similarity_graph()` from `uwot=0.1.14` and works well, has passed the pre-check and on its way to CRAN. Thank you for exporting the helpful graph-generation function.
